import { useState } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { authenticate } from "../services/api";
import { useAuth } from "../context/AuthContext";

export default function Account() {
  const [params] = useSearchParams();
  const [mode, setMode] = useState(params.get("mode") === "signup" ? "signup" : "login");
  const [submitted, setSubmitted] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const navigate = useNavigate();
  const { user, signIn, signOut } = useAuth();
  const submit = async (event) => { event.preventDefault(); setLoading(true); setError(""); const form = new FormData(event.currentTarget); try { const data = await authenticate(mode === "login" ? "login" : "signup", Object.fromEntries(form)); signIn(data); setSubmitted(true); window.setTimeout(() => navigate("/"), 900); } catch (requestError) { setError(requestError.message); } finally { setLoading(false); } };
  if (user) return <main className="account-page"><div className="account-panel profile-panel"><div className="account-mark">EC</div><p className="eyebrow">YOUR ACCOUNT</p><h1>Hello, {user.name.split(" ")[0]}.</h1><p className="account-intro">Your account is active and ready for your next order.</p><div className="profile-details"><div><span>Name</span><strong>{user.name}</strong></div><div><span>Email</span><strong>{user.email}</strong></div><div><span>Account type</span><strong>{user.role || "customer"}</strong></div></div><div className="profile-actions"><Link to="/shop" className="button button-coral">Continue shopping ↗</Link><button className="account-switch" onClick={signOut}>Sign out</button></div></div></main>;
  return <main className="account-page"><div className="account-panel"><div className="account-mark">EC</div><p className="eyebrow">YOUR ACCOUNT</p><h1>{mode === "login" ? "Welcome back." : "Join Ecommerce."}</h1><p className="account-intro">{mode === "login" ? "Sign in to see your orders and saved pieces." : "Create an account for a more personal shopping experience."}</p>{submitted ? <div className="account-success">You are all set. Taking you home ✓</div> : <form className="checkout-form" onSubmit={submit}>{mode === "signup" && <label>Full name<input name="name" required autoComplete="name" /></label>}<label>Email<input name="email" type="email" required autoComplete="email" /></label><label>Password<input name="password" type="password" minLength="8" required autoComplete={mode === "login" ? "current-password" : "new-password"} /></label>{error && <p className="account-error" role="alert">{error}</p>}<button className="button button-coral" type="submit" disabled={loading}>{loading ? "Please wait..." : mode === "login" ? "Log in ↗" : "Create account ↗"}</button></form>}<div className="account-perks"><span>Secure account</span><span>Order history</span><span>Saved pieces</span></div><button className="account-switch" onClick={() => { setMode(mode === "login" ? "signup" : "login"); setError(""); }}>{mode === "login" ? "Need an account? Sign up" : "Already have an account? Log in"}</button><Link to="/" className="underlined-link account-home">Back to shopping</Link></div></main>;
}